name: Plotly Calplot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Initialize Python 3.7
      uses: actions/setup-python@v1
      with: 
        python-version: 3.7
      
    - name: Install dependencies
      run: make install
      
    - name: Run formatter
      run: make lint
      
    - name: Run checks
      run: make checks

    - name: Run checks
      run: make checks

    - name: pypi deploy
      run: make pypi_deploy
