name: Plotly Calplot CI
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  push:
    branches: [ add-tests ]
  pull_request:
    branches: [ add-tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
  
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-$
        restore-keys: |
          poetry-$

  install:
    runs-on: ubuntu-latest
    steps:       
    - name: Install dependencies
      run: poetry install
      

  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Run formatter
      run: make lint

  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Run checks
      run: make checks

  deploy_to_pypi:
    runs-on: ubuntu-latest
    steps:
    - name: pypi deploy
      run: make pypi_deploy
